### ISSUE TITLE
default storage order

### ISSUE THREAD

**Issue by vbarrielle** [vbarrielle/dense_mats#2]
constructors should have a default storage order (probably C order if we want to be non-surprising to numpy users)

Some specific constructors for F order should also be added.

**Comment by daniel-vainsencher** [comment]
As an aside w.r.t. cooperating language's orderings, I've recently started integrating Rust code with R, and was surprised that it understands only F order (unless I missed something, new there as mentioned). OTOH, NumPy easily deals with both. 

That said, my opinion is the main criterion for most constructors should be convenience for native code (translated from papers). We should design elsewhere the optimal interface for inter-language operation. I don't think either order is significantly better universally, as long as we support both the default doesn't matter.
